// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connections.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const connectionByExternal = `-- name: ConnectionByExternal :one
SELECT id, user_id, platform, external_account_id, username, access_token_enc, token_expires_at, scopes, status, subscription_status, subscribed_fields, last_refreshed_at, created_at, updated_at
FROM connections
WHERE platform = $1
  AND external_account_id = $2
`

type ConnectionByExternalParams struct {
	Platform          string `json:"platform"`
	ExternalAccountID string `json:"external_account_id"`
}

func (q *Queries) ConnectionByExternal(ctx context.Context, arg ConnectionByExternalParams) (Connection, error) {
	row := q.db.QueryRow(ctx, connectionByExternal, arg.Platform, arg.ExternalAccountID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.ExternalAccountID,
		&i.Username,
		&i.AccessTokenEnc,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.Status,
		&i.SubscriptionStatus,
		&i.SubscribedFields,
		&i.LastRefreshedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const connectionByUser = `-- name: ConnectionByUser :one
SELECT id, user_id, platform, external_account_id, username, access_token_enc, token_expires_at, scopes, status, subscription_status, subscribed_fields, last_refreshed_at, created_at, updated_at
FROM connections
WHERE user_id = $1
ORDER BY created_at
LIMIT 1
`

func (q *Queries) ConnectionByUser(ctx context.Context, userID uuid.UUID) (Connection, error) {
	row := q.db.QueryRow(ctx, connectionByUser, userID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.ExternalAccountID,
		&i.Username,
		&i.AccessTokenEnc,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.Status,
		&i.SubscriptionStatus,
		&i.SubscribedFields,
		&i.LastRefreshedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createConnection = `-- name: CreateConnection :one
INSERT INTO connections (
    user_id, platform, external_account_id, username,
    access_token_enc, token_expires_at, scopes,
    status, subscription_status, subscribed_fields
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, user_id, platform, external_account_id, username, access_token_enc, token_expires_at, scopes, status, subscription_status, subscribed_fields, last_refreshed_at, created_at, updated_at
`

type CreateConnectionParams struct {
	UserID             uuid.UUID  `json:"user_id"`
	Platform           string     `json:"platform"`
	ExternalAccountID  string     `json:"external_account_id"`
	Username           string     `json:"username"`
	AccessTokenEnc     string     `json:"access_token_enc"`
	TokenExpiresAt     *time.Time `json:"token_expires_at"`
	Scopes             []string   `json:"scopes"`
	Status             string     `json:"status"`
	SubscriptionStatus string     `json:"subscription_status"`
	SubscribedFields   []string   `json:"subscribed_fields"`
}

func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, createConnection,
		arg.UserID,
		arg.Platform,
		arg.ExternalAccountID,
		arg.Username,
		arg.AccessTokenEnc,
		arg.TokenExpiresAt,
		arg.Scopes,
		arg.Status,
		arg.SubscriptionStatus,
		arg.SubscribedFields,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.ExternalAccountID,
		&i.Username,
		&i.AccessTokenEnc,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.Status,
		&i.SubscriptionStatus,
		&i.SubscribedFields,
		&i.LastRefreshedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSubscription = `-- name: SetSubscription :exec
UPDATE connections
SET subscription_status = $2,
    subscribed_fields   = $3,
    updated_at          = now()
WHERE id = $1
`

type SetSubscriptionParams struct {
	ID                 uuid.UUID `json:"id"`
	SubscriptionStatus string    `json:"subscription_status"`
	SubscribedFields   []string  `json:"subscribed_fields"`
}

func (q *Queries) SetSubscription(ctx context.Context, arg SetSubscriptionParams) error {
	_, err := q.db.Exec(ctx, setSubscription, arg.ID, arg.SubscriptionStatus, arg.SubscribedFields)
	return err
}

const updateConnectionTokens = `-- name: UpdateConnectionTokens :one
UPDATE connections
SET username         = $2,
    access_token_enc = $3,
    token_expires_at = $4,
    scopes           = $5,
    status           = $6,
    last_refreshed_at = now(),
    updated_at       = now()
WHERE id = $1
RETURNING id, user_id, platform, external_account_id, username, access_token_enc, token_expires_at, scopes, status, subscription_status, subscribed_fields, last_refreshed_at, created_at, updated_at
`

type UpdateConnectionTokensParams struct {
	ID             uuid.UUID  `json:"id"`
	Username       string     `json:"username"`
	AccessTokenEnc string     `json:"access_token_enc"`
	TokenExpiresAt *time.Time `json:"token_expires_at"`
	Scopes         []string   `json:"scopes"`
	Status         string     `json:"status"`
}

func (q *Queries) UpdateConnectionTokens(ctx context.Context, arg UpdateConnectionTokensParams) (Connection, error) {
	row := q.db.QueryRow(ctx, updateConnectionTokens,
		arg.ID,
		arg.Username,
		arg.AccessTokenEnc,
		arg.TokenExpiresAt,
		arg.Scopes,
		arg.Status,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.ExternalAccountID,
		&i.Username,
		&i.AccessTokenEnc,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.Status,
		&i.SubscriptionStatus,
		&i.SubscribedFields,
		&i.LastRefreshedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
