// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dm_outbox.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimDMJob = `-- name: ClaimDMJob :one
SELECT id, connection_id, rule_id, external_account_id, comment_id, actor_id, media_id, body, link, status, attempt_count, next_attempt_at, last_error, created_at, sent_at
FROM dm_outbox
WHERE status = 'pending'
  AND next_attempt_at <= now()
ORDER BY next_attempt_at
FOR UPDATE SKIP LOCKED
LIMIT 1
`

func (q *Queries) ClaimDMJob(ctx context.Context) (DmOutbox, error) {
	row := q.db.QueryRow(ctx, claimDMJob)
	var i DmOutbox
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.RuleID,
		&i.ExternalAccountID,
		&i.CommentID,
		&i.ActorID,
		&i.MediaID,
		&i.Body,
		&i.Link,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const deferJob = `-- name: DeferJob :exec
UPDATE dm_outbox
SET next_attempt_at = $2
WHERE id = $1
`

type DeferJobParams struct {
	ID            uuid.UUID `json:"id"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
}

func (q *Queries) DeferJob(ctx context.Context, arg DeferJobParams) error {
	_, err := q.db.Exec(ctx, deferJob, arg.ID, arg.NextAttemptAt)
	return err
}

const failJob = `-- name: FailJob :exec
UPDATE dm_outbox
SET status = 'failed',
    attempt_count = attempt_count + 1,
    last_error = $2
WHERE id = $1
`

type FailJobParams struct {
	ID        uuid.UUID `json:"id"`
	LastError *string   `json:"last_error"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.Exec(ctx, failJob, arg.ID, arg.LastError)
	return err
}

const insertDMJob = `-- name: InsertDMJob :execrows
INSERT INTO dm_outbox (
    connection_id, rule_id, external_account_id, comment_id,
    actor_id, media_id, body, link
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (comment_id) DO NOTHING
`

type InsertDMJobParams struct {
	ConnectionID      uuid.UUID `json:"connection_id"`
	RuleID            uuid.UUID `json:"rule_id"`
	ExternalAccountID string    `json:"external_account_id"`
	CommentID         string    `json:"comment_id"`
	ActorID           string    `json:"actor_id"`
	MediaID           *string   `json:"media_id"`
	Body              string    `json:"body"`
	Link              *string   `json:"link"`
}

func (q *Queries) InsertDMJob(ctx context.Context, arg InsertDMJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDMJob,
		arg.ConnectionID,
		arg.RuleID,
		arg.ExternalAccountID,
		arg.CommentID,
		arg.ActorID,
		arg.MediaID,
		arg.Body,
		arg.Link,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSent = `-- name: MarkSent :exec
UPDATE dm_outbox
SET status = 'sent', sent_at = now()
WHERE id = $1
`

func (q *Queries) MarkSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markSent, id)
	return err
}

const retryJob = `-- name: RetryJob :exec
UPDATE dm_outbox
SET attempt_count = attempt_count + 1,
    next_attempt_at = $2,
    last_error = $3
WHERE id = $1
`

type RetryJobParams struct {
	ID            uuid.UUID `json:"id"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
	LastError     *string   `json:"last_error"`
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) error {
	_, err := q.db.Exec(ctx, retryJob, arg.ID, arg.NextAttemptAt, arg.LastError)
	return err
}

const rulesForCache = `-- name: RulesForCache :many
SELECT r.id AS rule_id,
       r.connection_id,
       c.external_account_id,
       c.ig_id,
       r.media_id,
       r.keywords,
       r.response_message,
       r.response_link,
       r.require_follow
FROM rules r
JOIN connections c ON c.id = r.connection_id
WHERE r.status = 'active'
`

type RulesForCacheRow struct {
	RuleID            uuid.UUID `json:"rule_id"`
	ConnectionID      uuid.UUID `json:"connection_id"`
	ExternalAccountID string    `json:"external_account_id"`
	IgID              string    `json:"ig_id"`
	MediaID           *string   `json:"media_id"`
	Keywords          []string  `json:"keywords"`
	ResponseMessage   string    `json:"response_message"`
	ResponseLink      *string   `json:"response_link"`
	RequireFollow     bool      `json:"require_follow"`
}

func (q *Queries) RulesForCache(ctx context.Context) ([]RulesForCacheRow, error) {
	rows, err := q.db.Query(ctx, rulesForCache)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RulesForCacheRow{}
	for rows.Next() {
		var i RulesForCacheRow
		if err := rows.Scan(
			&i.RuleID,
			&i.ConnectionID,
			&i.ExternalAccountID,
			&i.IgID,
			&i.MediaID,
			&i.Keywords,
			&i.ResponseMessage,
			&i.ResponseLink,
			&i.RequireFollow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
