// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ConnectionByExternal(ctx context.Context, arg ConnectionByExternalParams) (Connection, error)
	ConnectionByUser(ctx context.Context, userID uuid.UUID) (Connection, error)
	CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error)
	CreateUser(ctx context.Context) (User, error)
	SetSubscription(ctx context.Context, arg SetSubscriptionParams) error
	TouchUserLogin(ctx context.Context, id uuid.UUID) error
	UpdateConnectionTokens(ctx context.Context, arg UpdateConnectionTokensParams) (Connection, error)
}

var _ Querier = (*Queries)(nil)
