// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate_limits.sql

package store

import (
	"context"
)

const deleteRateLimit = `-- name: DeleteRateLimit :exec
DELETE FROM rate_limits WHERE external_account_id = $1
`

// DeleteRateLimit drops an account's bucket (no FK to cascade through).
func (q *Queries) DeleteRateLimit(ctx context.Context, account string) error {
	_, err := q.db.Exec(ctx, deleteRateLimit, account)
	return err
}

const seedRateBucket = `-- name: SeedRateBucket :exec
INSERT INTO rate_limits (external_account_id, tokens, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (external_account_id) DO NOTHING
`

type SeedRateBucketParams struct {
	Account  string  `json:"account"`
	Capacity float64 `json:"capacity"`
}

// SeedRateBucket ensures a full bucket exists for the account. ON CONFLICT DO
// NOTHING means no write (and no dead tuple) after the first sighting.
func (q *Queries) SeedRateBucket(ctx context.Context, arg SeedRateBucketParams) error {
	_, err := q.db.Exec(ctx, seedRateBucket, arg.Account, arg.Capacity)
	return err
}

const tryConsumeToken = `-- name: TryConsumeToken :one
UPDATE rate_limits
SET tokens = LEAST($1::float8, tokens + EXTRACT(EPOCH FROM (now() - updated_at)) * $2::float8) - 1,
    updated_at = now()
WHERE external_account_id = $3
  AND LEAST($1::float8, tokens + EXTRACT(EPOCH FROM (now() - updated_at)) * $2::float8) >= 1
RETURNING tokens
`

type TryConsumeTokenParams struct {
	Capacity     float64 `json:"capacity"`
	RefillPerSec float64 `json:"refill_per_sec"`
	Account      string  `json:"account"`
}

// TryConsumeToken atomically refills then consumes one token, but only if at
// least one token is available after the refill (the WHERE guard). It returns
// the remaining tokens on success; zero rows (pgx.ErrNoRows) means denied. The
// single UPDATE takes the row lock, so concurrent callers can never double-spend.
func (q *Queries) TryConsumeToken(ctx context.Context, arg TryConsumeTokenParams) (float64, error) {
	row := q.db.QueryRow(ctx, tryConsumeToken, arg.Capacity, arg.RefillPerSec, arg.Account)
	var tokens float64
	err := row.Scan(&tokens)
	return tokens, err
}
