// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rules.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createRule = `-- name: CreateRule :one
INSERT INTO rules (
    connection_id, media_id, keywords, match_mode,
    response_message, response_link, require_follow, capture_email, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, connection_id, media_id, keywords, match_mode, response_message, response_link, require_follow, capture_email, status, created_at, updated_at
`

type CreateRuleParams struct {
	ConnectionID    uuid.UUID `json:"connection_id"`
	MediaID         *string   `json:"media_id"`
	Keywords        []string  `json:"keywords"`
	MatchMode       string    `json:"match_mode"`
	ResponseMessage string    `json:"response_message"`
	ResponseLink    *string   `json:"response_link"`
	RequireFollow   bool      `json:"require_follow"`
	CaptureEmail    bool      `json:"capture_email"`
	Status          string    `json:"status"`
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, createRule,
		arg.ConnectionID,
		arg.MediaID,
		arg.Keywords,
		arg.MatchMode,
		arg.ResponseMessage,
		arg.ResponseLink,
		arg.RequireFollow,
		arg.CaptureEmail,
		arg.Status,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.MediaID,
		&i.Keywords,
		&i.MatchMode,
		&i.ResponseMessage,
		&i.ResponseLink,
		&i.RequireFollow,
		&i.CaptureEmail,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRule = `-- name: DeleteRule :execrows
DELETE FROM rules
WHERE id = $1
  AND connection_id = $2
`

type DeleteRuleParams struct {
	ID           uuid.UUID `json:"id"`
	ConnectionID uuid.UUID `json:"connection_id"`
}

func (q *Queries) DeleteRule(ctx context.Context, arg DeleteRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRule, arg.ID, arg.ConnectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rulesByConnection = `-- name: RulesByConnection :many
SELECT id, connection_id, media_id, keywords, match_mode, response_message, response_link, require_follow, capture_email, status, created_at, updated_at
FROM rules
WHERE connection_id = $1
ORDER BY created_at DESC
`

func (q *Queries) RulesByConnection(ctx context.Context, connectionID uuid.UUID) ([]Rule, error) {
	rows, err := q.db.Query(ctx, rulesByConnection, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rule{}
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.MediaID,
			&i.Keywords,
			&i.MatchMode,
			&i.ResponseMessage,
			&i.ResponseLink,
			&i.RequireFollow,
			&i.CaptureEmail,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
