// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (last_login_at)
VALUES (now())
RETURNING id, last_login_at, created_at, updated_at
`

func (q *Queries) CreateUser(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, createUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchUserLogin = `-- name: TouchUserLogin :exec
UPDATE users
SET last_login_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchUserLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLogin, id)
	return err
}
