server {
    listen 80;
    server_tokens off;
    root /usr/share/nginx/html;

    location /loop-landing/ {
        try_files $uri $uri.html $uri/ =404;
    }

    location = /loop-landing {
        return 301 /loop-landing/;
    }
}
